server:
   port: 8080
   
spring:
   application:
      name: security
      
   datasource:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      url: ${DB_URL}
      driverClassName: ${DB_DRIVER}
      
   jpa:
      hibernate:
         connection:
            autocommit: true
   
   jackson:
      serialization:
         INDENT_OUTPUT: true
         
event:
  receiver:
    host: ${RECEIVER_HOST}
    port: ${RECEIVER_PORT:0}
    username: ${RECEIVER_USER:null}
    password: ${RECEIVER_PASSWORD:null}